### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by valeria1418** [SistemasTecTlaxiaco/infografia-valeria1418#1]
Realizar una infografía de los conceptos básicos de realidad aumentada, realidad virtual , características, funciones y aplicaciones

**Comment by valeria1418** [comment]
![Infografía](https://user-images.githubusercontent.com/61721683/110058374-d541fc00-7d27-11eb-8226-15e283b82ee1.jpeg)

**Comment by hiuta** [comment]
Calificacion 20

**Comment by josealfredo79** [comment]
Bien realizado y hecho.
